version: '2'
services:
  # brain is a python3 container
  brain:
    build:
      context: brain
    command: python main.py
    volumes:
      - ./brain:/app
    depends_on:
    - mongodb
    environment:
    - PYTHONUNBUFFERED=0

  it_brain:
    build:
      context: brain
    command: python main.py
    volumes:
      - ./brain:/app
    depends_on:
      - mongodb
    environment:
      - PYTHONUNBUFFERED=0
      - MONGODB_URI=mongodb://mongodb/botcycle_it
      - BOT_LANGUAGE=IT

#
#  slack_brain:
#    build:
#      context: brain
#    command: python main.py
#    volumes:
#      - ./brain:/app
#    depends_on:
#    - mongodb
#    environment:
#      - MONGODB_URI=mongodb://mongodb/slack_test
#      - WEBSOCKET_PATH=slack
#      - WEBSOCKET_TOKEN=GOTCHA
#      - PYTHONUNBUFFERED=0

  # container for mongo database
  mongodb:
    image: mongo:latest
    ports:
      # map the port of the container to the port of the host, in order to be able to connect via cli
      - "27017:27017"
    volumes:
      - mongo_storage_volume:/data/db
      # this shared folder will contain exported database in json
      - ./nlu/data/exported:/exported
      # provide to the container the script for exporting the database
      - ./nlu/data/export_mongo.sh:/export_mongo.sh
volumes:
  mongo_storage_volume: